{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import openai\n",
    "import pprint\n",
    "import logging\n",
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "openai.api_key = \"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\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# openai.Model.list()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "def retrieve_text_pair(text):\n",
    "    descriptions = []\n",
    "    commands = []\n",
    "    for line in text.split(\"\\n\"):\n",
    "        line = line.split(\":\")\n",
    "        if \"Description\" in line:\n",
    "            descriptions.append(':'.join(line[1:]))\n",
    "        elif \"Command\" in line:\n",
    "            commands.append(':'.join(line[1:]))\n",
    "        else:\n",
    "            pass\n",
    "    valid_len = min(len(descriptions), len(commands)) - 1\n",
    "    return descriptions[:valid_len], commands[:valid_len]\n",
    "\n",
    "# text_pair = retrieve_text_pair(text)\n",
    "# text_pair"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "def write_to_file(text_pair, description_path, command_path):\n",
    "    description_file = open(description_path, 'a')\n",
    "    command_file = open(command_path, 'a')\n",
    "    for d, c in zip(text_pair[0], text_pair[1]): \n",
    "        description_file.write(d.strip()+'\\n')\n",
    "        command_file.write(c.strip()+'\\n')\n",
    "    description_file.close()\n",
    "    command_file.close()\n",
    "\n",
    "# write_to_file(text_pair, \"output_description.txt\", \"output_command.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_response(description, command):\n",
    "    prompt = \\\n",
    "    f\"\"\"Generate 10 differnt bash commands and corresponding description:\n",
    "\n",
    "Description: {description}\n",
    "Command: {command}\n",
    "\"\"\"\n",
    "\n",
    "    response = openai.Completion.create(\n",
    "    engine=\"code-davinci-002\",\n",
    "    prompt=prompt,\n",
    "    temperature=0.0,\n",
    "    max_tokens=256,\n",
    "    top_p=1.0,\n",
    "    frequency_penalty=0.0,\n",
    "    presence_penalty=0.2\n",
    "    )\n",
    "    return response.choices[0][\"text\"]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "180 Set the write permission on the file 'filename'. chmod w filename\n",
      "181 Give execute permissions to the file named 'filename'. chmod x filename\n",
      "182 Allow the file 'filename' to be executed. chmod x filename\n",
      "183 Make the file 'filename' executable. chmod x filename\n",
      "184 Set the file 'filename' so it can be run. chmod x filename\n",
      "185 Grant execute rights to the file 'filename'. chmod x filename\n",
      "186 Remove write permission from the file 'filename' chmod -= filename\n",
      "187 Revoke write access to 'filename' chmod -= filename\n",
      "188 Take away the write ability for 'filename' chmod -= filename\n",
      "189 Deny write permission for the file 'filename' chmod -= filename\n",
      "190 Withdraw write access to the file 'filename' chmod -= filename\n",
      "191 For changing the ownership of a file/directory Chown user\n",
      "192 Change the ownership of the file to the specified user. Chown user\n",
      "193 Assign the file to a new owner, the user specified. Chown user\n",
      "194 Make the user the new owner of the file. Chown user\n",
      "195 Transfer the ownership of the file to the named user. Chown user\n",
      "196 Alter the ownership of the file so that it belongs to the specified user. Chown user\n",
      "197 change the user as well as group for a file or directory Chown user:group filename\n",
      "198 Assign a new owner to a file or directory Chown user:group filename\n",
      "199 Transfer ownership of a file or directory to a specified user Chown user:group filename\n",
      "200 Reassign ownership of a file or directory to a user Chown user:group filename\n",
      "201 Make a user the owner of a file or directory Chown user:group filename\n",
      "202 Specify a new owner for a file or directory Chown user:group filename\n",
      "203 Set a user as the owner of a file or directory Chown user:group filename\n",
      "204 Display the value of a variable echo $VARIABLE\n",
      "205 Show the contents of a variable echo $VARIABLE\n",
      "206 Print the value stored in a variable echo $VARIABLE\n",
      "207 Output the contents of a variable echo $VARIABLE\n",
      "208 Reveal the contents stored in a variable echo $VARIABLE\n",
      "209 Present the value of a variable. echo $VARIABLE\n",
      "210 Show the environment variables env\n",
      "211 Display the current environment settings env\n",
      "212 Print the shell environment information env\n",
      "213 Present the environment configurations env\n",
      "214 Reveal the system environment variables env\n",
      "215 Output the environment variables of the current shell session. env\n",
      "216 Create a new variable VARIABLE_NAME= variable_value\n",
      "217 Define a new variable and set its value VARIABLE_NAME= variable_value\n",
      "218 Establish a new variable and give it a value VARIABLE_NAME= variable_value\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py:19: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead\n",
      "  logging.warn(i, \"error: \", str(e))\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 217\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "219 Declare a new variable and assign it a value VARIABLE_NAME= variable_value\n",
      "220 Make a new variable and specify its value VARIABLE_NAME= variable_value\n",
      "221 Form a new variable and provide it with a value. VARIABLE_NAME= variable_value\n",
      "222 Remove a variable Unset\n",
      "223 Remove a variable Unset\n",
      "224 Delete a variable Unset\n",
      "225 Eliminate a variable Unset\n",
      "226 Undeclare a variable Unset\n",
      "227 Nullify a variable Unset\n",
      "228 Dispose of a variable. Unset\n",
      "229 To set value of an environment variable export Variable=value\n",
      "230 Assign the value \"value\" to a variable export Variable=value\n",
      "231 Define a variable with the value \"value\" export Variable=value\n",
      "232 Establish a variable with the value \"value\" export Variable=value\n",
      "233 Specify a variable and its value \"value\" export Variable=value\n",
      "234 Set a variable to the value \"value\" export Variable=value\n",
      "235 Create a variable and give it the value \"value\" export Variable=value\n",
      "236 Add a new user  of 'username' sudo adduser username\n",
      "237 Create a new  of 'username'  user with administrative privileges sudo adduser username\n",
      "238 Add a new  of 'username' user with root permissions sudo adduser username\n",
      "239 Establish a new user  of 'username' with superuser access sudo adduser username\n",
      "240 Grant root privileges to a new user  of 'username' sudo adduser username\n",
      "241 Create a new administrative user  of 'username' sudo adduser username\n",
      "242 change the password of a user sudo passwd -l 'username'\n",
      "243 Update a user's  of 'username' password sudo passwd -l 'username'\n",
      "244 Modify a user's  of 'username' password sudo passwd -l 'username'\n",
      "245 Reset a user's  of 'username' password sudo passwd -l 'username'\n",
      "246 Alter a user's  of 'username' password sudo passwd -l 'username'\n",
      "247 Change a user's  of 'username' password security. sudo passwd -l 'username'\n",
      "248 Remove a newly created user of 'username' sudo userdel -r 'username'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 247\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "249 Delete a user of 'username' and their related files sudo userdel -r 'username'\n",
      "250 Remove a user  of 'username' and their associated data sudo userdel -r 'username'\n",
      "251 Terminate a user  of 'username' and their belongings sudo userdel -r 'username'\n",
      "252 Erase a user  of 'username' and their files permanently sudo userdel -r 'username'\n",
      "253 Get rid of a user  of 'username' and their information sudo userdel -r 'username'\n",
      "254 Purge a user  of 'username' and their related assets. sudo userdel -r 'username'\n",
      "255 Assign a user of 'username' to an additional of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "256 Add a user of 'username' to a secondary of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "257 Grant a user of 'username' membership to another of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "258 Make a user of 'username' part of an extra of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "259 Give a user of 'username' access to an additional of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "260 Include a user of 'username' in a supplementary of \"groupname\" group sudo usermod -a -G GROUPNAME USERNAME\n",
      "261 Enroll a user of 'username' in an additional group of \"groupname\" membership sudo usermod -a -G GROUPNAME USERNAME\n",
      "262 Add a user of 'username' to a supplementary group of \"groupname\" membership sudo usermod -a -G GROUPNAME USERNAME\n",
      "263 To remove a user from a group sudo deluser USER GROUPNAME\n",
      "264 Remove a user account and its association with a group. sudo deluser USER GROUPNAME\n",
      "265 Delete a user account and their membership in a group. sudo deluser USER GROUPNAME\n",
      "266 Unregister a user and their group affiliation. sudo deluser USER GROUPNAME\n",
      "267 Eliminate a user and their connection to a group. sudo deluser USER GROUPNAME\n",
      "268 Purge a user account and the group it belongs to. sudo deluser USER GROUPNAME\n",
      "269 Shows information of all the users logged in finger\n",
      "270 Display information about a user on a Unix-like system. finger\n",
      "271 Show details about a specific user account. finger\n",
      "272 Get information about a particular user on a Unix system. finger\n",
      "273 Retrieve details about a user including login name, real name, and login time. finger\n",
      "274 Fetch information about a user, such as their login name, full name, and last login time. finger\n",
      "275 Gives information of a particular user finger username\n",
      "276 Display information about the specified user. finger username\n",
      "277 Show details about a specific user on the system. finger username\n",
      "278 Retrieve information about a particular user. finger username\n",
      "279 See information about the user with the specified username. finger username\n",
      "280 Get information such as login time, real name, and home directory of a user. finger username\n",
      "281 login into a remote Linux machine using SSH SSH username@ip-address\n",
      "282 Connect to a remote computer using the SSH protocol with the specified username and IP address. SSH username@ip-address\n",
      "283 Establish a secure shell connection to the remote machine using the given username and IP. SSH username@ip-address\n",
      "284 Log in to a remote system through SSH with the provided username and IP address. SSH username@ip-address\n",
      "285 Access a remote device over the internet securely with SSH and the specified username and IP. SSH username@ip-address\n",
      "286 Initiate a secure shell session to a remote machine with the provided username and IP address. SSH username@ip-address\n",
      "287 To ping and Analyzing network and host connections Ping hostname=\"sample_hostname\"\n",
      "288 Send a test message to the host named 'sample_hostname' to check its connectivity. Ping hostname=\"sample_hostname\"\n",
      "289 Check the reachability of 'sample_hostname' by sending a ping request. Ping hostname=\"sample_hostname\"\n",
      "290 Determine if 'sample_hostname' is reachable by sending a network test packet. Ping hostname=\"sample_hostname\"\n",
      "291 Verify the network connection to 'sample_hostname' by sending a ping. Ping hostname=\"sample_hostname\"\n",
      "292 Test the network connection to 'sample_hostname' by sending a network diagnostic packet. Ping hostname=\"sample_hostname\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 291\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "293 Display files in the current directory of a remote computer dir\n",
      "294 Show the contents of the current directory. dir\n",
      "295 Display a list of files and subdirectories in the current folder. dir\n",
      "296 List the items in the current working directory. dir\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 295\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "297 Examine the files and subdirectories present in the present location. dir\n",
      "298 Provide an overview of the files and folders in the current directory. dir\n",
      "299 change directory to “dirname” on a remote computer cd \"dirname\"\n",
      "300 Change the current working directory to 'dirname'. cd \"dirname\"\n",
      "301 Navigate to the directory named 'dirname'. cd \"dirname\"\n",
      "302 Go to the folder 'dirname'. cd \"dirname\"\n",
      "303 Enter the directory 'dirname'. cd \"dirname\"\n",
      "304 Switch to the directory 'dirname'. cd \"dirname\"\n",
      "305 upload ‘file’ from local to remote computer put file\n",
      "306 Upload a file. put file\n",
      "307 Send a file to a specified location. put file\n",
      "308 Transfer a file from the current device to another. put file\n",
      "309 Place a file into a designated directory. put file\n",
      "310 Copy a file to a target location. put file\n",
      "311 Download ‘file’ from remote to local computer get file\n",
      "312 Retrieve a file. get file\n",
      "313 Download a file. get file\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 312\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "314 Acquire a file. get file\n",
      "315 Fetch a file. get file\n",
      "316 Obtain a file. get file\n",
      "317 Logout quit\n",
      "318 Exit the terminal. quit\n",
      "319 End the session. quit\n",
      "320 Close the command prompt. quit\n",
      "321 Terminate the command line interface. quit\n",
      "322 Leave the command line interface and return to the previous interface. quit\n",
      "323 To send a process to the background bg\n",
      "324 Resume a stopped job in the background. bg\n",
      "325 Move a suspended process to run in the background. bg\n",
      "326 Start a job running in the background. bg\n",
      "327 Continue execution of a stopped task in the background. bg\n",
      "328 Make a previously stopped job run in the background. bg\n",
      "329 To run a stopped process in the foreground fg\n",
      "330 Bring a background process to the foreground. fg\n",
      "331 Make a background job the active process. fg\n",
      "332 Move a background task to the command line interface. fg\n",
      "333 Resume a stopped process in the foreground. fg\n",
      "334 Switch a background task to the forefront. fg\n",
      "335 Details on all Active Processes top\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 334\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "336 Display the processes running on the system and their resource usage. top\n",
      "337 Show the current status of system processes and their utilization of system resources. top\n",
      "338 Monitor the performance of processes in real-time. top\n",
      "339 View the active processes and their CPU, memory, and other resource usage statistics. top\n",
      "340 Track the most resource-intensive processes running on the system in real-time. top\n",
      "341 Give the status of processes running for a user ps\n",
      "342 Show the current processes running on the system. ps\n",
      "343 Display the list of active processes. ps\n",
      "344 List the processes currently in execution. ps\n",
      "345 Examine the tasks currently running on the system. ps\n",
      "346 View the active processes on the system and their status. ps\n",
      "347 Gives the status of a particular process ps PID\n",
      "348 Show information about the process with the specified process ID (PID). ps PID\n",
      "349 Display the details of the process identified by its PID. ps PID\n",
      "350 List the attributes of the process with PID. ps PID\n",
      "351 Examine the information of the process matching the PID provided. ps PID\n",
      "352 Retrieve information about the process indicated by its PID value. ps PID\n",
      "353 Gives the Process ID (PID) of a process pidof\n",
      "354 Find the process ID of a running program. pidof\n",
      "355 Get the identification number of a currently running process. pidof\n",
      "356 Retrieve the process identifier of a specific application. pidof\n",
      "357 Determine the process ID of a specified executable. pidof\n",
      "358 Locate the process ID for a running software program. pidof\n",
      "359 Kills a process kill PID\n",
      "360 Terminate the process with the specified process ID (PID). kill PID\n",
      "361 End the running task with the given PID number. kill PID\n",
      "362 Send a signal to end the process identified by PID. kill PID\n",
      "363 Stop the process with PID from running. kill PID\n",
      "364 Forcefully close the process with the PID indicated. kill PID\n",
      "365 Starts a process with a given priority nice\n",
      "366 Set the priority of a process to run with lower CPU utilization. nice\n",
      "367 Run a program with a lower priority than other processes. nice\n",
      "368 Execute a command at a lower priority to allow other processes to have more CPU time. nice\n",
      "369 Launch a process with reduced CPU resource allocation. nice\n",
      "370 Start a command with a lower CPU allocation for better system performance. nice\n",
      "371 Changes priority of an already running process renice\n",
      "372 Adjust the priority level of a running process. renice\n",
      "373 Change the scheduling priority of an active process. renice\n",
      "374 Modify the priority value assigned to a process that is already running. renice\n",
      "375 Alter the importance level of a process that is currently executing. renice\n",
      "376 Redefine the priority of a process that is in operation. renice\n",
      "377 Gives free hard disk space on your system df\n",
      "378 Show the amount of free disk space on all mounted file systems. df\n",
      "379 Display the available and used disk space on the system. df\n",
      "380 Check the amount of space occupied and the space available on the file systems. df\n",
      "381 See the disk space utilization of all mounted file systems. df\n",
      "382 View the amount of storage used and the storage remaining on all mounted file systems. df\n",
      "383 Gives free RAM on your system free\n",
      "384 Display the amount of free and used memory in the system. free\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 14, in read_input_and_process\n",
      "    text = get_response(des, com)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\4134653161.py\", line 9, in get_response\n",
      "    response = openai.Completion.create(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\completion.py\", line 25, in create\n",
      "    return super().create(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_resources\\abstract\\engine_api_resource.py\", line 153, in create\n",
      "    response, _, api_key = requestor.request(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 227, in request\n",
      "    resp, got_stream = self._interpret_response(result, stream)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 620, in _interpret_response\n",
      "    self._interpret_response_line(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\openai\\api_requestor.py\", line 680, in _interpret_response_line\n",
      "    raise self.handle_error_response(\n",
      "openai.error.RateLimitError: Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 1100, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 943, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 678, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\logging\\__init__.py\", line 368, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 196, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\runpy.py\", line 86, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\traitlets\\config\\application.py\", line 1043, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 728, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 215, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 603, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\base_events.py\", line 1906, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 513, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 502, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 409, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 729, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 423, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 540, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2945, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3000, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3203, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3382, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\sha\\Desktop\\NL2BASH simple\\.conda\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3442, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 22, in <module>\n",
      "    read_input_and_process(180, \"user_input.txt\", \"commands.txt\")\n",
      "  File \"C:\\Users\\sha\\AppData\\Local\\Temp\\ipykernel_33648\\1366258353.py\", line 19, in read_input_and_process\n",
      "    logging.warn(i, \"error: \", str(e))\n",
      "Message: 383\n",
      "Arguments: ('error: ', 'Rate limit reached for default-code-davinci-002 in organization org-DjQVqYz5nfmgxwIh0WLWNCrq on requests per min. Limit: 20.000000 / min. Current: 30.000000 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "385 Show the available and used system memory information. free\n",
      "386 List the amount of physical memory and swap memory that is unused. free\n",
      "387 Print the memory usage statistics. free\n",
      "388 Report the system's available and utilized memory resources. free\n"
     ]
    }
   ],
   "source": [
    "def read_input_and_process(start_index, input_description, input_command):\n",
    "    description_file = open(input_description, 'r', encoding=\"utf8\")\n",
    "    command_file = open(input_command, 'r', encoding=\"utf8\")\n",
    "    description_list = description_file.readlines()\n",
    "    command_list = command_file.readlines()\n",
    "    description_file.close()\n",
    "    command_file.close()\n",
    "    for i, (des, com) in enumerate(zip(description_list, command_list)):\n",
    "        if i < start_index:\n",
    "            continue\n",
    "        try:\n",
    "            print(i, des.strip(), com.strip())\n",
    "            logging.info(\"running line: \",i)\n",
    "            text = get_response(des, com)\n",
    "            text_pair = retrieve_text_pair(text)\n",
    "            write_to_file(text_pair, \"output_description.txt\", \"output_command.txt\")\n",
    "            time.sleep(5)\n",
    "        except Exception as e:\n",
    "            logging.warn(i, \"error: \", str(e))\n",
    "\n",
    "\n",
    "read_input_and_process(180, \"user_input.txt\", \"commands.txt\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "82fe7ed36f9ad6559ba51341c961e8276e59b84cbd1ed114aa757cf4a3f703a1"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
